ASAP = "asap"
CHOPIN_FE = "chopin_fe"
CPM = "cpm"

EXCERPTS = [
    {
        "id": "chopin-op25-6-thirds",
        "technique": "Double thirds",
        "composer": "Frédéric Chopin",
        "title": "Étude in G-sharp minor, Op. 25 No. 6",
        "bars": [4, 5],
        "hand": "right",
        "marking": "Allegro",
        "tempo": 120,
        "pedal": "none",
        "source": {"kind": CHOPIN_FE, "path": "kern/025-1b-LE-006.krn", "edition": "Lemoine first edition, Paris"},
        "verify": [{"kind": CHOPIN_FE, "path": "kern/025_1-6-1d-BH-006.krn"}],
        "note": "The right hand's trill in thirds, B–D♯ against C♯–E, breaks into a chromatic scale in thirds that climbs two octaves.",
    },
    {
        "id": "chopin-op25-8-sixths",
        "technique": "Double sixths",
        "composer": "Frédéric Chopin",
        "title": "Étude in D-flat major, Op. 25 No. 8",
        "bars": [1, 2],
        "hand": "right",
        "marking": "Vivace",
        "tempo": 69,
        "pedal": "beat",
        "source": {"kind": CHOPIN_FE, "path": "kern/025-1b-LE-008.krn", "edition": "Lemoine first edition, Paris"},
        "verify": [{"kind": ASAP, "path": "Chopin/Etudes_op_25/8/xml_score.musicxml"}],
        "note": "Legato sixths in the right hand, rocking between F–D♭ and G♭–E♭ in triplet eighths, with the left hand in broken intervals below.",
    },
    {
        "id": "beethoven-op13-broken-octaves",
        "technique": "Broken octaves",
        "composer": "Ludwig van Beethoven",
        "title": "Sonata No. 8 in C minor, Op. 13 “Pathétique”, I",
        "bars": [11, 12],
        "hand": "left",
        "marking": "Allegro di molto e con brio",
        "tempo": 240,
        "pedal": "none",
        "source": {"kind": ASAP, "path": "Beethoven/Piano_Sonatas/8-1/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "verify": [{"kind": CPM, "path": "subset_S/Beethoven/136_CPM_Sonata_No.8_C_minor_Opus_13_1/S_1296_CPM.mid"}],
        "note": "The start of the Allegro: the left hand drums broken octaves on C in eighth notes while the right hand enters with the theme.",
    },
    {
        "id": "liszt-mephisto-broken-octaves",
        "technique": "Broken octaves",
        "composer": "Franz Liszt",
        "title": "Mephisto Waltz No. 1, S. 514",
        "bars": [173, 176],
        "hand": "right",
        "marking": "Allegro vivace",
        "tempo": 120,
        "pedal": "none",
        "source": {"kind": ASAP, "path": "Liszt/Mephisto_Waltz/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "verify": [],
        "note": "The right hand snaps each note to its upper octave in sixteenths, sliding down the keyboard over a repeated left-hand chord.",
    },
    {
        "id": "chopin-op25-10-octaves",
        "technique": "Blocked octaves",
        "composer": "Frédéric Chopin",
        "title": "Étude in B minor, Op. 25 No. 10",
        "bars": [1, 2],
        "hand": "both",
        "marking": "Allegro con fuoco",
        "tempo": 132,
        "pedal": "none",
        "source": {"kind": CHOPIN_FE, "path": "kern/025-1b-LE-010.krn", "edition": "Lemoine first edition, Paris"},
        "verify": [{"kind": ASAP, "path": "Chopin/Etudes_op_25/10/xml_score.musicxml"}],
        "note": "Both hands in octaves, two octaves apart, creeping chromatically in triplet eighths from the very first beat.",
    },
    {
        "id": "chopin-op53-octaves",
        "technique": "Blocked octaves",
        "composer": "Frédéric Chopin",
        "title": "Polonaise in A-flat major, Op. 53",
        "bars": [85, 86],
        "hand": "left",
        "marking": "sotto voce, sempre staccato",
        "tempo": 92,
        "pedal": "none",
        "source": {"kind": CHOPIN_FE, "path": "kern/053-1-BH.krn", "edition": "Breitkopf & Härtel first edition, Leipzig"},
        "verify": [{"kind": ASAP, "path": "Chopin/Polonaises/53/xml_score.musicxml"}, {"kind": CPM, "path": "subset_S/Chopin/223_CPM_Polonaise_Ab_major_Opus_53/S_1394_CPM.mid"}],
        "note": "The E-major trio's left-hand ostinato: octaves E–D♯–C♯–B in sixteenths, repeated under quiet right-hand chords.",
    },
    {
        "id": "liszt-mephisto-leaps",
        "technique": "Wide leaps",
        "composer": "Franz Liszt",
        "title": "Mephisto Waltz No. 1, S. 514",
        "bars": [767, 770],
        "hand": "right",
        "marking": "Presto",
        "tempo": 132,
        "pedal": "none",
        "source": {"kind": ASAP, "path": "Liszt/Mephisto_Waltz/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "verify": [],
        "note": "In the Presto the right hand plays a single note, then jumps to a double octave one or two octaves higher, over and over at full speed.",
    },
    {
        "id": "liszt-campanella-leaps",
        "technique": "Wide leaps",
        "composer": "Franz Liszt",
        "title": "La campanella, Grandes études de Paganini S. 141 No. 3",
        "bars": [5, 6],
        "hand": "right",
        "marking": "Allegretto",
        "tempo": 96,
        "pedal": "beat",
        "source": {"kind": ASAP, "path": "Liszt/Gran_Etudes_de_Paganini/2_La_campanella/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "verify": [{"kind": CPM, "path": "subset_S/Liszt/328_CPM_Grandes_Etudes_de_Paganini_3_La_campanella/S_1469_CPM.mid"}],
        "note": "The theme sits on the thumb while the little finger leaps up to the bell note D♯ between every melody note.",
    },
    {
        "id": "beethoven-op53-repeated-chords",
        "technique": "Repeated chords",
        "composer": "Ludwig van Beethoven",
        "title": "Sonata No. 21 in C major, Op. 53 “Waldstein”, I",
        "bars": [1, 2],
        "hand": "both",
        "marking": "Allegro con brio",
        "tempo": 168,
        "pedal": "none",
        "source": {"kind": ASAP, "path": "Beethoven/Piano_Sonatas/21-1/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "verify": [{"kind": CPM, "path": "subset_S/Beethoven/100_CPM_Sonata_No.21_C_major_Waldstein_Opus_53_1/S_1306_CPM.mid"}],
        "note": "The opening: pianissimo repeated eighth-note chords low in the keyboard, to be kept perfectly even and quiet.",
    },
    {
        "id": "chopin-ballade1-scale",
        "technique": "Rapid scales",
        "composer": "Frédéric Chopin",
        "title": "Ballade No. 1 in G minor, Op. 23",
        "bars": [255, 255],
        "hand": "both",
        "marking": "Presto con fuoco",
        "tempo": 120,
        "pedal": "none",
        "source": {"kind": ASAP, "path": "Chopin/Ballades/1/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "verify": [{"kind": CPM, "path": "subset_S/Chopin/172_CPM_Ballad_G_minor_Opus_23/S_1354_CPM.mid"}],
        "note": "Near the end of the coda both hands race up the G-minor scale two octaves apart in one sweep before the closing chords.",
    },
    {
        "id": "chopin-op10-1-arpeggio",
        "technique": "Arpeggio figuration",
        "composer": "Frédéric Chopin",
        "title": "Étude in C major, Op. 10 No. 1",
        "bars": [1, 2],
        "hand": "right",
        "marking": "Allegro",
        "tempo": 160,
        "pedal": "bar",
        "source": {"kind": CHOPIN_FE, "path": "kern/010-1b-Sm-001.krn", "edition": "Schlesinger first edition, Berlin"},
        "verify": [{"kind": ASAP, "path": "Chopin/Etudes_op_10/1/xml_score.musicxml"}, {"kind": CPM, "path": "subset_S/Chopin/178_CPM_Etudes_Opus_10_1/S_1350_CPM.mid"}],
        "note": "Sixteenth-note arpeggios on C major stretch a tenth in every group, climbing four octaves and coming straight back down over a left-hand octave.",
    },
    {
        "id": "liszt-hr2-broken-chords",
        "technique": "Arpeggio figuration",
        "composer": "Franz Liszt",
        "title": "Hungarian Rhapsody No. 2, S. 244/2",
        "bars": [64, 66],
        "hand": "right",
        "marking": "Lassan",
        "tempo": 54,
        "pedal": "bar",
        "source": {"kind": CPM, "path": "subset_S/Liszt/335_CPM_19_Hungarian_Rhapsodies_2/S_1476_CPM.mid", "edition": "piano-midi.de sequence (Bernd Krueger)", "key_sharps": 4, "approx_bars": True, "tracks": "right", "spelling": ["B#", "C#", "D", "D#", "E", "E#", "F#", "G", "G#", "A", "A#", "B"]},
        "verify": [],
        "note": "In the Lassan the right hand pours broken C♯-major chords down and back up the keyboard in thirty-second notes.",
    },
    {
        "id": "ravel-alborada-repeated-notes",
        "technique": "Repeated notes",
        "composer": "Maurice Ravel",
        "title": "Alborada del gracioso, Miroirs No. 4",
        "bars": [47, 48],
        "hand": "right",
        "marking": "Assez vif",
        "tempo": 126,
        "pedal": "none",
        "source": {"kind": ASAP, "path": "Ravel/Miroirs/4_Alborada_del_gracioso/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "verify": [],
        "note": "The famous repeated-note passage: G♯ struck again and again in rapid triplet sixteenths, changing fingers on every note.",
    },
    {
        "id": "beethoven-op53-trill",
        "technique": "Trills",
        "composer": "Ludwig van Beethoven",
        "title": "Sonata No. 21 in C major, Op. 53 “Waldstein”, III",
        "bars": [485, 486],
        "hand": "right",
        "marking": "Prestissimo",
        "tempo": 120,
        "pedal": "bar",
        "source": {"kind": ASAP, "path": "Beethoven/Piano_Sonatas/21-3/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "manual_check": "Melody matches a second edition; trill speed differs between editions",
        "verify": [{"kind": CPM, "path": "subset_S/Beethoven/102_CPM_Sonata_No.21_C_major_Waldstein_Opus_53_3/S_1308_CPM.mid"}],
        "note": "The right hand keeps a trill going on G–A with its lower fingers while the upper fingers play the theme above it.",
    },
    {
        "id": "chopin-op10-11-tenths",
        "technique": "Tenth stretches",
        "composer": "Frédéric Chopin",
        "title": "Étude in E-flat major, Op. 10 No. 11",
        "bars": [1, 2],
        "hand": "both",
        "marking": "Allegretto",
        "tempo": 76,
        "pedal": "bar",
        "rolled": True,
        "source": {"kind": CHOPIN_FE, "path": "kern/010-1b-Sm-011.krn", "edition": "Schlesinger first edition, Berlin"},
        "verify": [{"kind": CHOPIN_FE, "path": "kern/010_7-12-1-KI-011.krn"}],
        "note": "Every chord is rolled and spans a tenth or more in each hand, with the melody on the top note of the right hand.",
    },
    {
        "id": "brahms-op118-2-three-two",
        "technique": "Three against two",
        "composer": "Johannes Brahms",
        "title": "Intermezzo in A major, Op. 118 No. 2",
        "bars": [49, 50],
        "hand": "both",
        "marking": "In tempo",
        "tempo": 66,
        "pedal": "beat",
        "source": {"kind": ASAP, "path": "Brahms/Six_Pieces_op_118/2/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "verify": [],
        "note": "The right-hand melody moves in plain eighths while the left hand rolls triplet arpeggios underneath: two against three on every beat.",
    },
    {
        "id": "chopin-op66-four-three",
        "technique": "Four against three",
        "composer": "Frédéric Chopin",
        "title": "Fantaisie-Impromptu in C-sharp minor, Op. 66",
        "bars": [5, 6],
        "hand": "both",
        "marking": "Allegro agitato",
        "tempo": 150,
        "pedal": "beat",
        "source": {"kind": CHOPIN_FE, "path": "kern/066-1-Sam.krn", "edition": "posthumous first edition"},
        "verify": [{"kind": CPM, "path": "subset_S/Chopin/236_CPM_Fantaisie_Impromptu_Opus_66/S_1395_CPM.mid"}],
        "note": "Right-hand sixteenths against left-hand triplet eighths: four notes against three on every beat.",
    },
    {
        "id": "chopin-op10-3-melody",
        "technique": "Melody over accompaniment",
        "composer": "Frédéric Chopin",
        "title": "Étude in E major, Op. 10 No. 3",
        "bars": [1, 4],
        "hand": "right",
        "marking": "Lento ma non troppo",
        "tempo": 50,
        "pedal": "beat",
        "source": {"kind": ASAP, "path": "Chopin/Etudes_op_10/3/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "verify": [],
        "manual_check": "Checked by hand against the Schlesinger first edition",
        "note": "The melody sits in the top fingers of the right hand while the same hand plays sixteenth-note accompaniment underneath it.",
    },
    {
        "id": "chopin-op25-5-inner-voice",
        "technique": "Inner voice projection",
        "composer": "Frédéric Chopin",
        "title": "Étude in E minor, Op. 25 No. 5",
        "bars": [46, 48],
        "hand": "left",
        "marking": "Più lento",
        "tempo": 66,
        "pedal": "beat",
        "source": {"kind": CHOPIN_FE, "path": "kern/025-1b-LE-005.krn", "edition": "Lemoine first edition, Paris"},
        "verify": [{"kind": ASAP, "path": "Chopin/Etudes_op_25/5/xml_score.musicxml"}],
        "note": "In the E-major middle section the melody moves into the left-hand thumb, in the middle of the texture, under right-hand arpeggios.",
    },
    {
        "id": "ravel-ondine-pedal",
        "technique": "Half pedalling",
        "composer": "Maurice Ravel",
        "title": "Ondine, Gaspard de la nuit No. 1",
        "bars": [2, 3],
        "hand": "both",
        "marking": "Lent",
        "tempo": 60,
        "pedal": "bar",
        "source": {"kind": ASAP, "path": "Ravel/Gaspard_de_la_Nuit/1_Ondine/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "verify": [{"kind": CPM, "path": "subset_S/Ravel/411_CPM_Gaspard_de_la_Uuit_Ondine/S_1538_CPM.mid"}],
        "note": "A pianissimo shimmer of repeated chords with the melody entering underneath: the pedal has to keep the haze alive without letting the tune blur.",
    },
    {
        "id": "schumann-toccata-endurance",
        "technique": "Sustained endurance",
        "composer": "Robert Schumann",
        "title": "Toccata in C major, Op. 7",
        "bars": [3, 6],
        "hand": "both",
        "marking": "Allegro",
        "tempo": 126,
        "pedal": "none",
        "source": {"kind": ASAP, "path": "Schumann/Toccata/xml_score.musicxml", "edition": "ASAP dataset encoding"},
        "verify": [],
        "note": "Nonstop sixteenths in double notes that keep going for pages: the right hand alternates C–E with B–F without a single rest.",
    },
]
