"""create dynamic catalog tables

Revision ID: a77858f33c61
Revises: 
Create Date: 2026-09-24 11:30:41.140074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = 'a77858f33c61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('achievements',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), server_default='0', nullable=False),
    sa.Column('gold_reward', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('code', name=op.f('uq_achievements_code'))
    )
    op.create_table('cosmetics',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.Enum('star_color', 'glow', 'nebula', 'link_style', name='cosmetic_kind'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_gold', sa.Integer(), server_default='0', nullable=False),
    sa.Column('min_level', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('price_gold >= 0', name=op.f('ck_cosmetics_price_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cosmetics')),
    sa.UniqueConstraint('code', name=op.f('uq_cosmetics_code'))
    )
    op.create_table('eras',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('start_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eras')),
    sa.UniqueConstraint('name', name=op.f('uq_eras_name'))
    )
    op.create_table('genres',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('family', sa.Enum('classical', 'jazz', 'pop', 'film_game', 'folk', 'other', name='genre_family'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    op.create_table('techniques',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Enum('dexterity', 'double_notes', 'octaves', 'leaps', 'chords', 'repeated_notes', 'trills', 'stretches', 'polyrhythm', 'voicing', 'pedaling', 'endurance', name='technique_category'), nullable=False),
    sa.Column('parent_technique_id', sa.Integer(), nullable=True),
    sa.Column('load_factor', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mechanic', sa.Text(), nullable=True),
    sa.Column('common_fault', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_technique_id'], ['techniques.id'], name=op.f('fk_techniques_parent_technique_id_techniques'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_techniques')),
    sa.UniqueConstraint('name', name=op.f('uq_techniques_name'))
    )
    op.create_index(op.f('ix_techniques_parent_technique_id'), 'techniques', ['parent_technique_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('years_playing', sa.SmallInteger(), nullable=True),
    sa.Column('self_level', sa.Enum('beginner', 'intermediate', 'advanced', 'professional', name='self_level'), nullable=True),
    sa.Column('hand_span_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('profile_visibility', sa.Enum('private', 'friends', 'public', name='profile_visibility'), server_default='friends', nullable=False),
    sa.Column('tier_quiz_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('composers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('death_year', sa.SmallInteger(), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=True),
    sa.Column('era_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('fun_fact', sa.Text(), nullable=True),
    sa.Column('signature_sound', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['era_id'], ['eras.id'], name=op.f('fk_composers_era_id_eras'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_composers'))
    )
    op.create_index(op.f('ix_composers_era_id'), 'composers', ['era_id'], unique=False)
    op.create_index(op.f('ix_composers_name'), 'composers', ['name'], unique=False)
    op.create_table('friendships',
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('addressee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'blocked', name='friendship_status'), server_default='pending', nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requester_id <> addressee_id', name=op.f('ck_friendships_not_self')),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], name=op.f('fk_friendships_addressee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_friendships_requester_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friendships')),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendships_pair')
    )
    op.create_index(op.f('ix_friendships_addressee_id'), 'friendships', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friendships_requester_id'), 'friendships', ['requester_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('delta_xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('delta_gold', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reason', sa.Enum('piece_learned', 'graded_performance', 'practice_session', 'drill_forged', 'pathway_started', 'achievement', 'purchase', 'adjustment', name='ledger_reason'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ref_type', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.create_table('load_alerts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('load_total', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('severity', sa.Enum('info', 'caution', 'rest', name='load_severity'), server_default='info', nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_load_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_load_alerts')),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_load_alerts_user_week')
    )
    op.create_index(op.f('ix_load_alerts_user_id'), 'load_alerts', ['user_id'], unique=False)
    op.create_index(op.f('ix_load_alerts_week_start'), 'load_alerts', ['week_start'], unique=False)
    op.create_table('performances',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('venue', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_performances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performances'))
    )
    op.create_index(op.f('ix_performances_event_date'), 'performances', ['event_date'], unique=False)
    op.create_index(op.f('ix_performances_user_id'), 'performances', ['user_id'], unique=False)
    op.create_table('polyrhythm_attempts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ratio_left', sa.SmallInteger(), nullable=False),
    sa.Column('ratio_right', sa.SmallInteger(), nullable=False),
    sa.Column('bpm', sa.SmallInteger(), nullable=False),
    sa.Column('mean_offset_ms', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('accuracy_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bpm BETWEEN 20 AND 300', name=op.f('ck_polyrhythm_attempts_bpm_range')),
    sa.CheckConstraint('ratio_left > 0 AND ratio_right > 0', name=op.f('ck_polyrhythm_attempts_ratio_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_polyrhythm_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polyrhythm_attempts'))
    )
    op.create_index(op.f('ix_polyrhythm_attempts_user_id'), 'polyrhythm_attempts', ['user_id'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('free', 'live_listening', 'forge_drill', 'sight_reading', 'polyrhythm', name='practice_mode'), server_default='free', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('perceived_tension', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_practice_sessions_session_order')),
    sa.CheckConstraint('perceived_tension IS NULL OR perceived_tension BETWEEN 1 AND 5', name=op.f('ck_practice_sessions_tension_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_practice_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_sessions'))
    )
    op.create_index(op.f('ix_practice_sessions_started_at'), 'practice_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_practice_sessions_user_id'), 'practice_sessions', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id', name=op.f('pk_user_achievements'))
    )
    op.create_table('user_cosmetics',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cosmetic_id', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('equipped', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['cosmetic_id'], ['cosmetics.id'], name=op.f('fk_user_cosmetics_cosmetic_id_cosmetics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_cosmetics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'cosmetic_id', name=op.f('pk_user_cosmetics'))
    )
    op.create_table('user_genre_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_user_genre_preferences_genre_id_genres'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_genre_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'genre_id', name=op.f('pk_user_genre_preferences'))
    )
    op.create_table('user_technique_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.Column('self_rating', sa.Enum('struggle', 'neutral', 'strength', name='self_rating'), server_default='neutral', nullable=False),
    sa.Column('proficiency_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('proficiency_score IS NULL OR proficiency_score BETWEEN 0 AND 10', name=op.f('ck_user_technique_profiles_proficiency_range')),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], name=op.f('fk_user_technique_profiles_technique_id_techniques'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_technique_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'technique_id', name=op.f('pk_user_technique_profiles'))
    )
    op.create_table('wallets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('gold', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lifetime_xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lifetime_gold', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gold >= 0', name=op.f('ck_wallets_gold_non_negative')),
    sa.CheckConstraint('xp >= 0', name=op.f('ck_wallets_xp_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_wallets'))
    )
    op.create_table('pieces',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('composer_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('catalog_number', sa.String(length=40), nullable=True),
    sa.Column('key_signature', sa.String(length=20), nullable=True),
    sa.Column('year_composed', sa.SmallInteger(), nullable=True),
    sa.Column('difficulty_score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('mechanical_load', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('parent_piece_id', sa.Integer(), nullable=True),
    sa.Column('movement_number', sa.SmallInteger(), nullable=True),
    sa.Column('is_user_created', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('technique_vector', pgvector.sqlalchemy.Vector(dim=64), nullable=True),
    sa.Column('tempo_marking', sa.String(length=80), nullable=True),
    sa.Column('mood', sa.String(length=80), nullable=True),
    sa.Column('scene', sa.Text(), nullable=True),
    sa.Column('historical_note', sa.Text(), nullable=True),
    sa.Column('fun_fact', sa.Text(), nullable=True),
    sa.Column('syllabus_grade', sa.String(length=40), nullable=True),
    sa.Column('external_source', sa.String(length=40), nullable=True),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('metadata_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_generation_model', sa.String(length=60), nullable=True),
    sa.Column('custom_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('difficulty_score BETWEEN 0 AND 100', name=op.f('ck_pieces_difficulty_range')),
    sa.CheckConstraint('mechanical_load BETWEEN 0 AND 100', name=op.f('ck_pieces_mechanical_load_range')),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], name=op.f('fk_pieces_composer_id_composers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_pieces_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_pieces_genre_id_genres'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_piece_id'], ['pieces.id'], name=op.f('fk_pieces_parent_piece_id_pieces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pieces'))
    )
    op.create_index(op.f('ix_pieces_composer_id'), 'pieces', ['composer_id'], unique=False)
    op.create_index(op.f('ix_pieces_genre_id'), 'pieces', ['genre_id'], unique=False)
    op.create_index(op.f('ix_pieces_parent_piece_id'), 'pieces', ['parent_piece_id'], unique=False)
    op.create_index(op.f('ix_pieces_title'), 'pieces', ['title'], unique=False)
    op.create_table('user_composer_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('rank IS NULL OR rank > 0', name=op.f('ck_user_composer_preferences_rank_positive')),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], name=op.f('fk_user_composer_preferences_composer_id_composers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_composer_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'composer_id', name=op.f('pk_user_composer_preferences'))
    )
    op.create_table('passages',
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('start_measure', sa.Integer(), nullable=False),
    sa.Column('end_measure', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('difficulty_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('source', sa.Enum('catalog', 'analyzer', 'user', name='passage_source'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('practice_cue', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('end_measure >= start_measure', name=op.f('ck_passages_measure_order')),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], name=op.f('fk_passages_piece_id_pieces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passages'))
    )
    op.create_index(op.f('ix_passages_piece_id'), 'passages', ['piece_id'], unique=False)
    op.create_table('piece_link_notes',
    sa.Column('low_piece_id', sa.Integer(), nullable=False),
    sa.Column('high_piece_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.Enum('composer', 'technique', 'era_genre', name='link_type'), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('low_piece_id < high_piece_id', name=op.f('ck_piece_link_notes_ordered_pair')),
    sa.ForeignKeyConstraint(['high_piece_id'], ['pieces.id'], name=op.f('fk_piece_link_notes_high_piece_id_pieces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['low_piece_id'], ['pieces.id'], name=op.f('fk_piece_link_notes_low_piece_id_pieces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_piece_link_notes')),
    sa.UniqueConstraint('low_piece_id', 'high_piece_id', 'link_type', name='uq_piece_link_notes_edge')
    )
    op.create_index(op.f('ix_piece_link_notes_high_piece_id'), 'piece_link_notes', ['high_piece_id'], unique=False)
    op.create_index(op.f('ix_piece_link_notes_low_piece_id'), 'piece_link_notes', ['low_piece_id'], unique=False)
    op.create_table('piece_load_profiles',
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('octave_density', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_stretch_semitones', sa.SmallInteger(), nullable=True),
    sa.Column('repeated_chord_density', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes_per_second_peak', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('load_index', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], name=op.f('fk_piece_load_profiles_piece_id_pieces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('piece_id', name=op.f('pk_piece_load_profiles'))
    )
    op.create_table('piece_prerequisites',
    sa.Column('target_piece_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_piece_id', sa.Integer(), nullable=False),
    sa.Column('overlap_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source', sa.Enum('curated', 'computed', 'ai', name='prerequisite_source'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('target_piece_id <> prerequisite_piece_id', name=op.f('ck_piece_prerequisites_not_self')),
    sa.ForeignKeyConstraint(['prerequisite_piece_id'], ['pieces.id'], name=op.f('fk_piece_prerequisites_prerequisite_piece_id_pieces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_piece_id'], ['pieces.id'], name=op.f('fk_piece_prerequisites_target_piece_id_pieces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_piece_prerequisites')),
    sa.UniqueConstraint('target_piece_id', 'prerequisite_piece_id', name='uq_piece_prerequisites_pair')
    )
    op.create_index(op.f('ix_piece_prerequisites_prerequisite_piece_id'), 'piece_prerequisites', ['prerequisite_piece_id'], unique=False)
    op.create_index(op.f('ix_piece_prerequisites_target_piece_id'), 'piece_prerequisites', ['target_piece_id'], unique=False)
    op.create_table('piece_techniques',
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint('weight BETWEEN 0 AND 1', name=op.f('ck_piece_techniques_weight_range')),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], name=op.f('fk_piece_techniques_piece_id_pieces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], name=op.f('fk_piece_techniques_technique_id_techniques'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('piece_id', 'technique_id', name=op.f('pk_piece_techniques'))
    )
    op.create_table('recommendations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_piece_id', sa.Integer(), nullable=False),
    sa.Column('recommended_piece_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('suggested', 'accepted', 'dismissed', name='recommendation_status'), server_default='suggested', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 0 AND 1', name=op.f('ck_recommendations_score_range')),
    sa.CheckConstraint('target_piece_id <> recommended_piece_id', name=op.f('ck_recommendations_not_self')),
    sa.ForeignKeyConstraint(['recommended_piece_id'], ['pieces.id'], name=op.f('fk_recommendations_recommended_piece_id_pieces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_piece_id'], ['pieces.id'], name=op.f('fk_recommendations_target_piece_id_pieces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    sa.UniqueConstraint('user_id', 'target_piece_id', 'recommended_piece_id', name='uq_recommendations_triple')
    )
    op.create_index(op.f('ix_recommendations_recommended_piece_id'), 'recommendations', ['recommended_piece_id'], unique=False)
    op.create_index(op.f('ix_recommendations_target_piece_id'), 'recommendations', ['target_piece_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('repertoire_entries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('wishlist', 'learning', 'polishing', 'performance_ready', 'retired', name='repertoire_status'), server_default='learning', nullable=False),
    sa.Column('is_top_ten', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('top_ten_rank', sa.SmallInteger(), nullable=True),
    sa.Column('current_tempo_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('target_tempo_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('top_ten_rank IS NULL OR top_ten_rank BETWEEN 1 AND 10', name=op.f('ck_repertoire_entries_top_ten_range')),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], name=op.f('fk_repertoire_entries_piece_id_pieces'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_repertoire_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repertoire_entries')),
    sa.UniqueConstraint('user_id', 'piece_id', name='uq_repertoire_entries_user_piece')
    )
    op.create_index(op.f('ix_repertoire_entries_piece_id'), 'repertoire_entries', ['piece_id'], unique=False)
    op.create_index(op.f('ix_repertoire_entries_user_id'), 'repertoire_entries', ['user_id'], unique=False)
    op.create_table('sight_reading_exercises',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('style_composer_id', sa.Integer(), nullable=True),
    sa.Column('target_piece_id', sa.Integer(), nullable=True),
    sa.Column('technique_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('musicxml_key', sa.Text(), nullable=True),
    sa.Column('notation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('self_score', sa.SmallInteger(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('difficulty IS NULL OR difficulty BETWEEN 0 AND 10', name=op.f('ck_sight_reading_exercises_difficulty_range')),
    sa.CheckConstraint('self_score IS NULL OR self_score BETWEEN 1 AND 5', name=op.f('ck_sight_reading_exercises_self_score_range')),
    sa.ForeignKeyConstraint(['style_composer_id'], ['composers.id'], name=op.f('fk_sight_reading_exercises_style_composer_id_composers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_piece_id'], ['pieces.id'], name=op.f('fk_sight_reading_exercises_target_piece_id_pieces'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], name=op.f('fk_sight_reading_exercises_technique_id_techniques'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sight_reading_exercises_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sight_reading_exercises'))
    )
    op.create_index(op.f('ix_sight_reading_exercises_user_id'), 'sight_reading_exercises', ['user_id'], unique=False)
    op.create_table('drills',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('drill_type', sa.Enum('rhythm_variant', 'transposition', 'hands_separate', 'cortot_reduction', 'polyrhythm', 'voicing', name='drill_type'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('musicxml_key', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], name=op.f('fk_drills_passage_id_passages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_drills_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drills'))
    )
    op.create_index(op.f('ix_drills_passage_id'), 'drills', ['passage_id'], unique=False)
    op.create_index(op.f('ix_drills_user_id'), 'drills', ['user_id'], unique=False)
    op.create_table('passage_techniques',
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint('weight BETWEEN 0 AND 1', name=op.f('ck_passage_techniques_weight_range')),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], name=op.f('fk_passage_techniques_passage_id_passages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], name=op.f('fk_passage_techniques_technique_id_techniques'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('passage_id', 'technique_id', name=op.f('pk_passage_techniques'))
    )
    op.create_table('performance_program',
    sa.Column('performance_id', sa.Uuid(), nullable=False),
    sa.Column('repertoire_entry_id', sa.Uuid(), nullable=False),
    sa.Column('program_order', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('program_order > 0', name=op.f('ck_performance_program_program_order_positive')),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], name=op.f('fk_performance_program_performance_id_performances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repertoire_entry_id'], ['repertoire_entries.id'], name=op.f('fk_performance_program_repertoire_entry_id_repertoire_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('performance_id', 'repertoire_entry_id', name=op.f('pk_performance_program'))
    )
    op.create_table('practice_plans',
    sa.Column('repertoire_entry_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repertoire_entry_id'], ['repertoire_entries.id'], name=op.f('fk_practice_plans_repertoire_entry_id_repertoire_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_plans'))
    )
    op.create_index(op.f('ix_practice_plans_repertoire_entry_id'), 'practice_plans', ['repertoire_entry_id'], unique=False)
    op.create_table('submissions',
    sa.Column('repertoire_entry_id', sa.Uuid(), nullable=False),
    sa.Column('submission_type', sa.Enum('text', 'pdf', 'audio', name='submission_type'), nullable=False),
    sa.Column('processing_status', sa.Enum('queued', 'processing', 'done', 'failed', name='processing_status'), server_default='queued', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repertoire_entry_id'], ['repertoire_entries.id'], name=op.f('fk_submissions_repertoire_entry_id_repertoire_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    op.create_index(op.f('ix_submissions_repertoire_entry_id'), 'submissions', ['repertoire_entry_id'], unique=False)
    op.create_table('analyses',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('analyzer_name', sa.String(length=60), nullable=False),
    sa.Column('analyzer_version', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_analyses_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index(op.f('ix_analyses_submission_id'), 'analyses', ['submission_id'], unique=False)
    op.create_table('audio_submissions',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('is_full_run_through', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_verification', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('midi_key', sa.Text(), nullable=True),
    sa.Column('tempo_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interpretation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_audio_submissions_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('pk_audio_submissions'))
    )
    op.create_table('pdf_submissions',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('page_count', sa.SmallInteger(), nullable=True),
    sa.Column('musicxml_key', sa.Text(), nullable=True),
    sa.Column('omr_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_pdf_submissions_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('pk_pdf_submissions'))
    )
    op.create_table('plan_steps',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.SmallInteger(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('passage_id', sa.Integer(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('est_days', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'active', 'done', name='plan_step_status'), server_default='todo', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('step_order > 0', name=op.f('ck_plan_steps_step_order_positive')),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], name=op.f('fk_plan_steps_passage_id_passages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], name=op.f('fk_plan_steps_piece_id_pieces'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['practice_plans.id'], name=op.f('fk_plan_steps_plan_id_practice_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_steps')),
    sa.UniqueConstraint('plan_id', 'step_order', name='uq_plan_steps_order')
    )
    op.create_index(op.f('ix_plan_steps_passage_id'), 'plan_steps', ['passage_id'], unique=False)
    op.create_index(op.f('ix_plan_steps_piece_id'), 'plan_steps', ['piece_id'], unique=False)
    op.create_index(op.f('ix_plan_steps_plan_id'), 'plan_steps', ['plan_id'], unique=False)
    op.create_table('session_items',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('repertoire_entry_id', sa.Uuid(), nullable=True),
    sa.Column('passage_id', sa.Integer(), nullable=True),
    sa.Column('drill_id', sa.Uuid(), nullable=True),
    sa.Column('minutes', sa.SmallInteger(), nullable=True),
    sa.Column('load_units', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('minutes IS NULL OR minutes >= 0', name=op.f('ck_session_items_minutes_non_negative')),
    sa.ForeignKeyConstraint(['drill_id'], ['drills.id'], name=op.f('fk_session_items_drill_id_drills'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], name=op.f('fk_session_items_passage_id_passages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repertoire_entry_id'], ['repertoire_entries.id'], name=op.f('fk_session_items_repertoire_entry_id_repertoire_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], name=op.f('fk_session_items_session_id_practice_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_items'))
    )
    op.create_index(op.f('ix_session_items_drill_id'), 'session_items', ['drill_id'], unique=False)
    op.create_index(op.f('ix_session_items_passage_id'), 'session_items', ['passage_id'], unique=False)
    op.create_index(op.f('ix_session_items_repertoire_entry_id'), 'session_items', ['repertoire_entry_id'], unique=False)
    op.create_index(op.f('ix_session_items_session_id'), 'session_items', ['session_id'], unique=False)
    op.create_table('text_submissions',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_text_submissions_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('pk_text_submissions'))
    )
    op.create_table('passage_assessments',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('tempo_stability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('voicing_balance', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('restart_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('memory_slip', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('flagged_by', sa.Enum('ai', 'user', name='flagged_by'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_passage_assessments_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], name=op.f('fk_passage_assessments_passage_id_passages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passage_assessments'))
    )
    op.create_index(op.f('ix_passage_assessments_analysis_id'), 'passage_assessments', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_passage_assessments_passage_id'), 'passage_assessments', ['passage_id'], unique=False)
    op.create_table('readiness_scores',
    sa.Column('repertoire_entry_id', sa.Uuid(), nullable=False),
    sa.Column('audio_submission_id', sa.Uuid(), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('tempo_stability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('restart_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('memory_slip_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_score IS NULL OR overall_score BETWEEN 0 AND 100', name=op.f('ck_readiness_scores_overall_range')),
    sa.ForeignKeyConstraint(['audio_submission_id'], ['audio_submissions.submission_id'], name=op.f('fk_readiness_scores_audio_submission_id_audio_submissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repertoire_entry_id'], ['repertoire_entries.id'], name=op.f('fk_readiness_scores_repertoire_entry_id_repertoire_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readiness_scores'))
    )
    op.create_index(op.f('ix_readiness_scores_audio_submission_id'), 'readiness_scores', ['audio_submission_id'], unique=False)
    op.create_index(op.f('ix_readiness_scores_repertoire_entry_id'), 'readiness_scores', ['repertoire_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readiness_scores_repertoire_entry_id'), table_name='readiness_scores')
    op.drop_index(op.f('ix_readiness_scores_audio_submission_id'), table_name='readiness_scores')
    op.drop_table('readiness_scores')
    op.drop_index(op.f('ix_passage_assessments_passage_id'), table_name='passage_assessments')
    op.drop_index(op.f('ix_passage_assessments_analysis_id'), table_name='passage_assessments')
    op.drop_table('passage_assessments')
    op.drop_table('text_submissions')
    op.drop_index(op.f('ix_session_items_session_id'), table_name='session_items')
    op.drop_index(op.f('ix_session_items_repertoire_entry_id'), table_name='session_items')
    op.drop_index(op.f('ix_session_items_passage_id'), table_name='session_items')
    op.drop_index(op.f('ix_session_items_drill_id'), table_name='session_items')
    op.drop_table('session_items')
    op.drop_index(op.f('ix_plan_steps_plan_id'), table_name='plan_steps')
    op.drop_index(op.f('ix_plan_steps_piece_id'), table_name='plan_steps')
    op.drop_index(op.f('ix_plan_steps_passage_id'), table_name='plan_steps')
    op.drop_table('plan_steps')
    op.drop_table('pdf_submissions')
    op.drop_table('audio_submissions')
    op.drop_index(op.f('ix_analyses_submission_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_submissions_repertoire_entry_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_practice_plans_repertoire_entry_id'), table_name='practice_plans')
    op.drop_table('practice_plans')
    op.drop_table('performance_program')
    op.drop_table('passage_techniques')
    op.drop_index(op.f('ix_drills_user_id'), table_name='drills')
    op.drop_index(op.f('ix_drills_passage_id'), table_name='drills')
    op.drop_table('drills')
    op.drop_index(op.f('ix_sight_reading_exercises_user_id'), table_name='sight_reading_exercises')
    op.drop_table('sight_reading_exercises')
    op.drop_index(op.f('ix_repertoire_entries_user_id'), table_name='repertoire_entries')
    op.drop_index(op.f('ix_repertoire_entries_piece_id'), table_name='repertoire_entries')
    op.drop_table('repertoire_entries')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_target_piece_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommended_piece_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('piece_techniques')
    op.drop_index(op.f('ix_piece_prerequisites_target_piece_id'), table_name='piece_prerequisites')
    op.drop_index(op.f('ix_piece_prerequisites_prerequisite_piece_id'), table_name='piece_prerequisites')
    op.drop_table('piece_prerequisites')
    op.drop_table('piece_load_profiles')
    op.drop_index(op.f('ix_piece_link_notes_low_piece_id'), table_name='piece_link_notes')
    op.drop_index(op.f('ix_piece_link_notes_high_piece_id'), table_name='piece_link_notes')
    op.drop_table('piece_link_notes')
    op.drop_index(op.f('ix_passages_piece_id'), table_name='passages')
    op.drop_table('passages')
    op.drop_table('user_composer_preferences')
    op.drop_index(op.f('ix_pieces_title'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_parent_piece_id'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_genre_id'), table_name='pieces')
    op.drop_index(op.f('ix_pieces_composer_id'), table_name='pieces')
    op.drop_table('pieces')
    op.drop_table('wallets')
    op.drop_table('user_technique_profiles')
    op.drop_table('user_genre_preferences')
    op.drop_table('user_cosmetics')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_practice_sessions_user_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_started_at'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_polyrhythm_attempts_user_id'), table_name='polyrhythm_attempts')
    op.drop_table('polyrhythm_attempts')
    op.drop_index(op.f('ix_performances_user_id'), table_name='performances')
    op.drop_index(op.f('ix_performances_event_date'), table_name='performances')
    op.drop_table('performances')
    op.drop_index(op.f('ix_load_alerts_week_start'), table_name='load_alerts')
    op.drop_index(op.f('ix_load_alerts_user_id'), table_name='load_alerts')
    op.drop_table('load_alerts')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_friendships_requester_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_addressee_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_composers_name'), table_name='composers')
    op.drop_index(op.f('ix_composers_era_id'), table_name='composers')
    op.drop_table('composers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_techniques_parent_technique_id'), table_name='techniques')
    op.drop_table('techniques')
    op.drop_table('genres')
    op.drop_table('eras')
    op.drop_table('cosmetics')
    op.drop_table('achievements')
    # ### end Alembic commands ###
